name: 🏭 Cut Mod Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Semver Bump Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  cut_release:
    name: "Cut Release"
    uses: open-goal/mod-bundling-tools/.github/workflows/mod-bundler.yml@v1
    with:
      semverBump: ${{ inputs.bump }}
      metadataName: "Jak II - August Build"
      metadataDescription: "Mimics the Jak II August 2003 Review build which allows for consite skip"
      metadataSupportedGames: "jak2"
      metadataAuthors: "barg,zed"
      metadataTags: "speedrunning,gameplay-mod"
      metadataWebsiteUrl: "https://github.com/OpenGOAL-Mods/OG-Jak2-AugustBuild/blob/main/README.md"
      skipMacOS: true
      skipLinux: true
      toolingBinaryDir: "out/build/Release/bin"
      gameAssetsDir: "game/assets"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
